// <auto-generated />
using FilmArsivApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmArsivApp.Migrations
{
    [DbContext(typeof(VeritabaniBaglantisi))]
    partial class VeritabaniBaglantisiModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("FilmArsivApp.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfisYolu")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Puan")
                        .HasColumnType("REAL");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YayinYili")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Filmler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Truman Show, doğduğu günden itibaren tüm yaşamı 7/24 kameralarla kaydedilen ve dünya çapında bir realite şovunda yayınlandığından habersiz olan sıradan bir sigortacı, Truman Burbank'in hayatını anlatır. Kusursuz sanılan sahte bir dünyada yaşayan Truman, gizemli olaylar sonucu durumdan şüphelenip gerçeğin peşine düşer.",
                            AfisYolu = "truman.jpeg",
                            FilmAdi = "The Truman Show",
                            Puan = 8.0999999999999996,
                            Tur = "Komedi",
                            YayinYili = 1998
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Büyükanne ve büyükbabalarını ziyarete giden iki kardeşin, onların evinde karşılaştıkları tuhaf ve ürkütücü olaylar.",
                            AfisYolu = "visit.jpeg",
                            FilmAdi = "The Visit",
                            Puan = 6.2999999999999998,
                            Tur = "Korku",
                            YayinYili = 2015
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Sese duyarlı, ölümcül yaratıkların dünyayı istila etmesiyle sessizce hayatta kalmaya çalışan bir ailenin hikayesi.",
                            AfisYolu = "silence.jpeg",
                            FilmAdi = "The Silence",
                            Puan = 5.2999999999999998,
                            Tur = "Korku",
                            YayinYili = 2019
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Hindistan'ın en iyi mühendislik okulundaki üç arkadaşın, eğitim sistemindeki ezberciliğe karşı duruşu ve dostlukları.",
                            AfisYolu = "idiots.jpeg",
                            FilmAdi = "3 Idiots",
                            Puan = 8.4000000000000004,
                            Tur = "Komedi",
                            YayinYili = 2009
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Düşük IQ'lu ama sevgi dolu bir adamın, saf kalbiyle 20. yüzyılın en önemli tarihi olaylarına yön vermesi ve büyük aşkı.",
                            AfisYolu = "forrest.jpeg",
                            FilmAdi = "Forrest Gump",
                            Puan = 8.8000000000000007,
                            Tur = "Romantik",
                            YayinYili = 1994
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Amerikan İç Savaşı sonrası dönemde büyüyen, karakterleri birbirinden tamamen farklı dört kız kardeşin yaşam mücadelesi.",
                            AfisYolu = "little.jpeg",
                            FilmAdi = "Little Women",
                            Puan = 7.7999999999999998,
                            Tur = "Romantik",
                            YayinYili = 2019
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Küçük bir kızın zihnindeki beş temel duygunun (Neşe, Üzüntü, Öfke, Korku, Tiksinti) onu yönlendirme çabası.",
                            AfisYolu = "inside.jpeg",
                            FilmAdi = "Inside Out",
                            Puan = 8.0999999999999996,
                            Tur = "Animasyon",
                            YayinYili = 2015
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Felçli bir askerin, Pandora gezegenindeki yerli halk olan Na'vilerle bağ kurup doğayı korumak için kendi ırkına karşı savaşması.",
                            AfisYolu = "avatar.jpeg",
                            FilmAdi = "Avatar",
                            Puan = 7.9000000000000004,
                            Tur = "Aksiyon",
                            YayinYili = 2009
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Fakir bir ailenin, türlü kurnazlıklarla zengin bir ailenin evinde çalışmaya başlamasıyla gelişen trajikomik ve karanlık olaylar.",
                            AfisYolu = "parasite.jpeg",
                            FilmAdi = "Parasite",
                            Puan = 8.5,
                            Tur = "Dram",
                            YayinYili = 2019
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Bir Nazi subayının sekiz yaşındaki oğlu ile toplama kampındaki Yahudi bir çocuğun tellerin ardındaki masum dostluğu.",
                            AfisYolu = "boy.jpeg",
                            FilmAdi = "The Boy in the Striped Pajamas",
                            Puan = 7.7000000000000002,
                            Tur = "Dram",
                            YayinYili = 2008
                        },
                        new
                        {
                            Id = 11,
                            Aciklama = "Yaşlı bir baloncu ile küçük bir izcinin, uçan bir evle Güney Amerika'ya doğru çıktıkları macera dolu yolculuk.",
                            AfisYolu = "up.jpeg",
                            FilmAdi = "Up",
                            Puan = 8.3000000000000007,
                            Tur = "Animasyon",
                            YayinYili = 2009
                        },
                        new
                        {
                            Id = 12,
                            Aciklama = "Fakir ve temiz kalpli bir çocuk olan Charlie'nin, gizemli çikolata fabrikasını gezme hakkı kazanması ve fabrikadaki mucizeler.",
                            AfisYolu = "charlie.jpeg",
                            FilmAdi = "Charlie and the Chocolate Factory",
                            Puan = 6.7000000000000002,
                            Tur = "Komedi",
                            YayinYili = 2005
                        },
                        new
                        {
                            Id = 13,
                            Aciklama = "İkinci Dünya Savaşı sırasında Alman bir iş adamının, fabrikasında çalıştırarak binin üzerinde Yahudi'nin hayatını kurtarması.",
                            AfisYolu = "list.jpeg",
                            FilmAdi = "Schindler's List",
                            Puan = 9.0,
                            Tur = "Dram",
                            YayinYili = 1993
                        },
                        new
                        {
                            Id = 14,
                            Aciklama = "Haksız yere müebbet hapse çarptırılan bir bankacının, hapishane koşullarına karşı umudunu yitirmeden kurduğu dostluk ve kaçış planı.",
                            AfisYolu = "shaws.jpeg",
                            FilmAdi = "The Shawshank Redemption",
                            Puan = 9.3000000000000007,
                            Tur = "Dram",
                            YayinYili = 1994
                        },
                        new
                        {
                            Id = 15,
                            Aciklama = "New York'taki güçlü bir İtalyan mafya ailesinin gizli dünyası ve babasının yerine geçmek zorunda kalan Michael'ın dönüşümü.",
                            AfisYolu = "godfather.jpeg",
                            FilmAdi = "The Godfather",
                            Puan = 9.1999999999999993,
                            Tur = "Suç",
                            YayinYili = 1972
                        },
                        new
                        {
                            Id = 16,
                            Aciklama = "Monoton hayatından sıkılan bir sigortacının, karizmatik bir sabun satıcısıyla tanışıp yeraltında gizli bir dövüş kulübü kurması.",
                            AfisYolu = "fight.jpeg",
                            FilmAdi = "Fight Club",
                            Puan = 8.8000000000000007,
                            Tur = "Dram",
                            YayinYili = 1999
                        },
                        new
                        {
                            Id = 17,
                            Aciklama = "Yaşadığı dünyanın aslında yapay bir simülasyon olduğunu öğrenen bilgisayar programcısı Neo'nun insanlığı kurtarma savaşı.",
                            AfisYolu = "matrix.jpeg",
                            FilmAdi = "The Matrix",
                            Puan = 8.6999999999999993,
                            Tur = "Bilim Kurgu",
                            YayinYili = 1999
                        },
                        new
                        {
                            Id = 18,
                            Aciklama = "Toplum tarafından dışlanan ve görmezden gelinen komedyen Arthur Fleck'in, karanlık ve kaotik bir suç liderine dönüşmesi.",
                            AfisYolu = "joker.jpeg",
                            FilmAdi = "Joker",
                            Puan = 8.6999999999999993,
                            Tur = "Suç",
                            YayinYili = 2019
                        },
                        new
                        {
                            Id = 19,
                            Aciklama = "Dünyanın geleceği tehlikeye girdiğinde, insanlığın yaşayabileceği yeni bir gezegen bulmak için solucan deliğinden geçen astronotların hikayesi.",
                            AfisYolu = "inter.jpeg",
                            FilmAdi = "Interstellar",
                            Puan = 8.6999999999999993,
                            Tur = "Bilim Kurgu",
                            YayinYili = 2014
                        },
                        new
                        {
                            Id = 20,
                            Aciklama = "Mafyaya hayran büyüyen ve genç yaşta örgüte giren Henry Hill'in, yeraltı dünyasındaki yükselişini ve ardından gelen çöküşünü anlatan biyografi.",
                            AfisYolu = "good.jpeg",
                            FilmAdi = "GoodFellas",
                            Puan = 8.6999999999999993,
                            Tur = "Suç",
                            YayinYili = 1990
                        },
                        new
                        {
                            Id = 21,
                            Aciklama = "İkinci Dünya Savaşı sırasında toplama kampına götürülen Yahudi bir babanın, oğlunu korumak için yaşadıkları vahşeti bir oyun gibi göstermesi.",
                            AfisYolu = "life.jpeg",
                            FilmAdi = "Life Is Beautiful",
                            Puan = 8.5999999999999996,
                            Tur = "Dram",
                            YayinYili = 1997
                        },
                        new
                        {
                            Id = 22,
                            Aciklama = "Genç bir FBI ajanının, başka bir seri katili yakalayabilmek için dahi ve yamyam bir psikiyatrist olan Hannibal Lecter'ın zihnine girmesi.",
                            AfisYolu = "lambs.jpeg",
                            FilmAdi = "The Silence of the Lambs",
                            Puan = 8.5999999999999996,
                            Tur = "Suç",
                            YayinYili = 1991
                        },
                        new
                        {
                            Id = 23,
                            Aciklama = "Hristiyanlığın 7 ölümcül günahını rehber edinerek cinayetler işleyen bir seri katilin peşine düşen iki dedektifin hikayesi.",
                            AfisYolu = "seven.jpeg",
                            FilmAdi = "Seven",
                            Puan = 8.5999999999999996,
                            Tur = "Suç",
                            YayinYili = 1995
                        },
                        new
                        {
                            Id = 24,
                            Aciklama = "Bir hapishane gardiyanı ile mucizevi iyileştirme güçlerine sahip, devasa ama son derece uysal bir idam mahkumunun dokunaklı öyküsü.",
                            AfisYolu = "green.jpeg",
                            FilmAdi = "The Green Mile",
                            Puan = 8.5999999999999996,
                            Tur = "Dram",
                            YayinYili = 1999
                        },
                        new
                        {
                            Id = 25,
                            Aciklama = "Ailesi katledilen ve köle pazarında gladyatör olarak satılan Romalı bir generalin, imparatordan intikam almak için arenada verdiği mücadele.",
                            AfisYolu = "gladiator.jpeg",
                            FilmAdi = "Gladiator",
                            Puan = 8.5,
                            Tur = "Aksiyon",
                            YayinYili = 2000
                        },
                        new
                        {
                            Id = 26,
                            Aciklama = "Cinayetle suçlanan bir genç hakkında karar vermek zorunda olan 12 jüri üyesinin, bir odada verdikleri psikolojik ve ahlaki adalet savaşı.",
                            AfisYolu = "angry.jpeg",
                            FilmAdi = "12 Angry Men",
                            Puan = 9.0,
                            Tur = "Dram",
                            YayinYili = 1957
                        },
                        new
                        {
                            Id = 27,
                            Aciklama = "Ölüleri görebildiğini iddia eden küçük bir çocuk ile ona yardım etmeye çalışan çocuk psikoloğunun gizemli ve sarsıcı hikayesi.",
                            AfisYolu = "sixth.jpeg",
                            FilmAdi = "The Sixth Sense",
                            Puan = 8.1999999999999993,
                            Tur = "Gerilim",
                            YayinYili = 1999
                        },
                        new
                        {
                            Id = 28,
                            Aciklama = "Şizofreni hastalığıyla mücadele eden dahi matematikçi John Nash'in, bu zorlu sürece rağmen kazandığı Nobel Ödülü'ne uzanan hayatı.",
                            AfisYolu = "mind.jpeg",
                            FilmAdi = "A Beautiful Mind",
                            Puan = 8.1999999999999993,
                            Tur = "Biyografi",
                            YayinYili = 2001
                        },
                        new
                        {
                            Id = 29,
                            Aciklama = "Ünlü bir Avrupa otelinin konsiyerji ile bellboy'unun, paha biçilemez bir rönesans tablosunun çalınmasıyla başlayan absürt maceraları.",
                            AfisYolu = "grand.jpeg",
                            FilmAdi = "The Grand Budapest Hotel",
                            Puan = 8.0999999999999996,
                            Tur = "Komedi",
                            YayinYili = 2014
                        },
                        new
                        {
                            Id = 30,
                            Aciklama = "1960'ların Amerika'sında, beyaz ailelerin yanında çalışan siyahi hizmetçilerin maruz kaldığı ırkçılığı ve onlarla röportaj yapan genç bir yazarın hikayesini anlatır.",
                            AfisYolu = "help.jpeg",
                            FilmAdi = "The Help",
                            Puan = 8.0999999999999996,
                            Tur = "Dram",
                            YayinYili = 2011
                        },
                        new
                        {
                            Id = 31,
                            Aciklama = "Disleksi (öğrenme güçlüğü) nedeniyle çevresi tarafından tembel ve başarısız kabul edilen bir çocuğun, idealist bir resim öğretmeniyle hayatının değişmesi.",
                            AfisYolu = "like.jpeg",
                            FilmAdi = "Like Stars on Earth",
                            Puan = 8.3000000000000007,
                            Tur = "Dram",
                            YayinYili = 2007
                        },
                        new
                        {
                            Id = 32,
                            Aciklama = "Hayatlarından memnun olmayan iki ev kadınının, sahte alışveriş kuponları basarak milyon dolarlık bir dolandırıcılık şebekesi kurması.",
                            AfisYolu = "queen.jpeg",
                            FilmAdi = "Queenpins",
                            Puan = 6.4000000000000004,
                            Tur = "Komedi",
                            YayinYili = 2021
                        },
                        new
                        {
                            Id = 33,
                            Aciklama = "Evlat edindikleri 9 yaşındaki Esther adındaki küçük kızın, göründüğü kadar masum olmadığını fark eden bir ailenin yaşadığı dehşet.",
                            AfisYolu = "orphan.jpeg",
                            FilmAdi = "Orphan",
                            Puan = 7.0,
                            Tur = "Korku",
                            YayinYili = 2009
                        },
                        new
                        {
                            Id = 34,
                            Aciklama = "Sahipleri odada yokken canlanan oyuncakların dünyasını ve odaya yeni gelen Buzz Lightyear ile eski lider Woody'nin rekabetini anlatan klasik.",
                            AfisYolu = "toy.jpeg",
                            FilmAdi = "Toy Story",
                            Puan = 8.3000000000000007,
                            Tur = "Animasyon",
                            YayinYili = 1995
                        },
                        new
                        {
                            Id = 35,
                            Aciklama = "Yamaç paraşütü kazası sonrası felç kalan zengin bir aristokrat ile ona bakıcılık yapması için işe alınan varoşlardan gelen bir gencin samimi dostluğu.",
                            AfisYolu = "intouchables.jpeg",
                            FilmAdi = "The Intouchables",
                            Puan = 8.5,
                            Tur = "Biyografi",
                            YayinYili = 2011
                        },
                        new
                        {
                            Id = 36,
                            Aciklama = "Amcasının ihaneti yüzünden babasını kaybeden ve krallıktan sürülen genç aslan Simba'nın, büyüyüp tahtını geri alma mücadelesi.",
                            AfisYolu = "lion.jpeg",
                            FilmAdi = "The Lion King",
                            Puan = 8.5,
                            Tur = "Animasyon",
                            YayinYili = 1994
                        },
                        new
                        {
                            Id = 37,
                            Aciklama = "İkinci Dünya Savaşı sırasında Polonyalı dahi bir Yahudi piyanistin, Varşova gettolarında hayatta kalabilmek için verdiği trajik yaşam savaşı.",
                            AfisYolu = "pianist.jpeg",
                            FilmAdi = "The Pianist",
                            Puan = 8.5,
                            Tur = "Biyografi",
                            YayinYili = 2002
                        },
                        new
                        {
                            Id = 38,
                            Aciklama = "Çılgın bir bilim insanının icat ettiği zaman makinesiyle yanlışlıkla 30 yıl geçmişe giden Marty'nin, kendi doğumunu riske atması ve geleceği düzeltme çabası.",
                            AfisYolu = "back.jpeg",
                            FilmAdi = "Back to the Future",
                            Puan = 8.5,
                            Tur = "Bilim Kurgu",
                            YayinYili = 1985
                        },
                        new
                        {
                            Id = 39,
                            Aciklama = "Saplantılı ilişkilerin, sırlar ve ihanetlerle örülü tehlikeli bir intikam oyununa dönüşmesini konu alan modern bir psikolojik gerilim.",
                            AfisYolu = "obsession.jpeg",
                            FilmAdi = "Obsession",
                            Puan = 8.1999999999999993,
                            Tur = "Gerilim",
                            YayinYili = 2025
                        },
                        new
                        {
                            Id = 40,
                            Aciklama = "Güneşi ve dolayısıyla Dünya'yı yok etmek üzere olan bir felaketi önlemek için uzayda tek başına uyanan bir astronotun, insanlığı kurtarma görevi.",
                            AfisYolu = "project.jpeg",
                            FilmAdi = "Project Hail Mary",
                            Puan = 8.3000000000000007,
                            Tur = "Bilim Kurgu",
                            YayinYili = 2026
                        },
                        new
                        {
                            Id = 41,
                            Aciklama = "Küçük bir kızın söylediği masum bir yalan yüzünden, haksız yere çocuk taciziyle suçlanan ve hayatı altüst olan bir kreş öğretmeninin dramı.",
                            AfisYolu = "hunt.jpeg",
                            FilmAdi = "The Hunt",
                            Puan = 8.3000000000000007,
                            Tur = "Dram",
                            YayinYili = 2012
                        },
                        new
                        {
                            Id = 42,
                            Aciklama = "Geleceğin endüstriyel şehrinde, yeraltında köle gibi çalışan işçiler ile yukarıda lüks içinde yaşayan elit tabaka arasındaki sınıf çatışmasını anlatan sessiz sinema şaheseri.",
                            AfisYolu = "metro.jpeg",
                            FilmAdi = "Metropolis",
                            Puan = 8.1999999999999993,
                            Tur = "Bilim Kurgu",
                            YayinYili = 1927
                        },
                        new
                        {
                            Id = 43,
                            Aciklama = "Fizikçi J. Robert Oppenheimer'ın, İkinci Dünya Savaşı'nı bitiren atom bombasının geliştirilme sürecindeki rolü ve sonrasında yaşadığı vicdani hesaplaşma.",
                            AfisYolu = "oppen.jpeg",
                            FilmAdi = "Oppenheimer",
                            Puan = 8.1999999999999993,
                            Tur = "Biyografi",
                            YayinYili = 2023
                        },
                        new
                        {
                            Id = 44,
                            Aciklama = "Klonlanan dinozorların sergilenmesi için kurulan bir adadaki güvenlik sisteminin çökmesi sonucu, adada mahsur kalan insanların hayatta kalma savaşı.",
                            AfisYolu = "park.jpeg",
                            FilmAdi = "Jurassic Park",
                            Puan = 8.1999999999999993,
                            Tur = "Macera",
                            YayinYili = 1993
                        },
                        new
                        {
                            Id = 45,
                            Aciklama = "Küçük kızları kaçırılan bir babanın, polisin yetersiz kaldığını düşünerek adaleti kendi elleriyle aramaya başlaması ve sınırları zorlaması.",
                            AfisYolu = "prison.jpeg",
                            FilmAdi = "Prisoners",
                            Puan = 8.1999999999999993,
                            Tur = "Suç",
                            YayinYili = 2013
                        },
                        new
                        {
                            Id = 46,
                            Aciklama = "İnsanlar tarafından yakalanıp bir akvaryuma konan küçük kayıp balık Nemo'yu bulmak için, okyanusu boydan boya geçen korumacı babasının maceraları.",
                            AfisYolu = "nemo.jpeg",
                            FilmAdi = "Finding Nemo",
                            Puan = 8.1999999999999993,
                            Tur = "Animasyon",
                            YayinYili = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
